"""The handful of filters worth showing above the fold, per category.

123 controls in one form is not a form. The canvas shows this short list first and collapses the
rest behind "Все фильтры (N)".

**Explicit data, deliberately, not a heuristic.** A rule like "promote anything whose name contains
price/origin/email" was measured against the live signatures and promoted 90 of Steam's 123 fields —
it curated nothing. Which filters matter for sniping is a judgement about the marketplace, and
judgements do not compress into a regex.

Every name here is checked against the live signature by ``test_curated_names_all_exist``, so a
pylzt rename turns this file red instead of silently dropping a control from the top of the form.
"""

from __future__ import annotations

from typing import Final

from app.domain.market.categories import SearchableCategory

# Every name here is in the 18 filters ALL 21 categories share, which is what makes it a safe
# fallback for a category added by a future pylzt upgrade before anyone curates it: it cannot name a
# filter that category lacks. `test_the_core_fallback_is_valid_for_every_category` pins that.
_CORE: Final[tuple[str, ...]] = (
    "pmin",
    "title",
    "origin",
    "not_origin",
    "nsb",
    "sb",
    "currency",
    "email_login_data",
    "email_provider",
    "tag_id",
    "not_tag_id",
    "user_id",
)

# What a sniper actually filters on, per category. The shape repeats — price floor, how the account
# was obtained, whether it is on hold, mail quality, age — and then the two or three numbers that
# make THAT category's accounts worth different money (robux, vbucks, town hall level, rank).
_BY_CATEGORY: Final[dict[SearchableCategory, tuple[str, ...]]] = {
    SearchableCategory.STEAM: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "daybreak",
        "reg",
        "last_trans_date_period",
        "game",
        "inv_game",
        "inv_min",
        "win_count_min",
        "trade_ban",
        "limit",
        "market",
        "no_vac",
        "currency",
    ),
    SearchableCategory.FORTNITE: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "daybreak",
        "reg",
        "smin",
        "vbmin",
        "skin",
        "pickaxe",
        "platform",
        "change_email",
        "no_trans",
        "lmin",
        "country",
        "temp_email",
    ),
    SearchableCategory.RIOT: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "daybreak",
        "rmin",
        "valorant_rank_type",
        "valorant_region",
        "valorant_smin",
        "valorant_level_min",
        "lol_region",
        "lol_level_min",
        "skin",
        "knife",
        "vp_min",
        "country",
    ),
    SearchableCategory.TELEGRAM: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "daybreak",
        "spam",
        "password",
        "premium",
        "country",
        "min_channels",
        "min_chats",
        "min_contacts",
        "min_stars",
        "min_gifts",
        "min_admin",
        "dc_id",
        "allow_geo_spamblock",
        "min_id",
    ),
    SearchableCategory.DISCORD: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "reg",
        "nitro",
        "nitro_type",
        "badge",
        "condition",
        "boosts_min",
        "billing",
        "field_2fa",
        "min_servers",
        "language",
        "country",
        "tel",
    ),
    SearchableCategory.ROBLOX: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "reg",
        "robux_min",
        "limited_price_min",
        "ugc_limited_price_min",
        "friends_min",
        "followers_min",
        "subscription",
        "verified",
        "age_verified",
        "voice",
        "gamepass_min",
        "inv_min",
        "credit_balance_min",
        "country",
    ),
    SearchableCategory.EPICGAMES: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "daybreak",
        "game",
        "gmin",
        "balance_min",
        "hours_played",
        "rl_purchases",
        "change_email",
        "no_trans",
        "last_trans_date_period",
        "country",
        "eg",
        "rewards_balance_min",
    ),
    SearchableCategory.BATTLENET: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "daybreak",
        "game",
        "balance_min",
        "no_bans",
        "edit_btag",
        "changeable_fn",
        "real_id",
        "parent_control",
        "country",
        "tel",
        "eg",
    ),
    SearchableCategory.EA: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "game",
        "gmin",
        "has_ban",
        "al_rank_min",
        "al_level_min",
        "hours_played",
        "subscription",
        "steam_connected",
        "transactions",
        "country",
    ),
    SearchableCategory.ESCAPEFROMTARKOV: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "region",
        "version",
        "reg",
        "level_min",
        "pve",
        "side",
        "sc",
    ),
    SearchableCategory.GIFTS: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "subscription",
        "subscription_length",
        "subscription_period",
        "tag_id",
        "user_id",
    ),
    SearchableCategory.INSTAGRAM: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "reg",
        "followers_min",
        "post_min",
        "cookies",
        "login_without_cookies",
        "country",
        "tel",
    ),
    SearchableCategory.MINECRAFT: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "reg",
        "java",
        "bedrock",
        "capes_min",
        "change_nickname",
        "hypixel_ban",
        "rank_hypixel",
        "level_hypixel_min",
        "net_worth_hypixel_skyblock_min",
        "subscription",
        "nickname_length_min",
        "can_change_details",
        "minecoins_min",
        "country",
    ),
    SearchableCategory.SOCIALCLUB: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "daybreak",
        "game",
        "level_min",
        "cash_min",
        "bank_cash_min",
        "tag_id",
        "user_id",
    ),
    SearchableCategory.SUPERCELL: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "daybreak",
        "brawl_level_min",
        "brawl_cup_min",
        "brawlers_min",
        "brawl_pass",
        "royale_level_min",
        "royale_cup_min",
        "king_level_min",
        "clash_level_min",
        "town_hall_level_min",
        "creation_year_min",
        "tel",
    ),
    SearchableCategory.TIKTOK: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "reg",
        "followers_min",
        "like_min",
        "post_min",
        "coins_min",
        "verified",
        "cookie_login",
        "can_stream",
        "tel",
    ),
    SearchableCategory.UPLAY: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "daybreak",
        "game",
        "gmin",
        "r6_level_min",
        "r6_rank_min",
        "r6_ban",
        "r6_smin",
        "r6_operators_min",
        "balance_min",
        "subscription",
        "reg",
        "country",
    ),
    SearchableCategory.VPN: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "service",
        "subscription_length",
        "subscription_period",
        "autorenewal",
        "tag_id",
        "user_id",
    ),
    SearchableCategory.WARFACE: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "daybreak",
        "rank_min",
        "bonus_rank_min",
        "kredits_min",
        "total_kredits_min",
        "tel",
    ),
    SearchableCategory.HYTALE: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "edition",
        "profiles_min",
        "tag_id",
        "user_id",
    ),
    SearchableCategory.LLM: (
        "pmin",
        "title",
        "origin",
        "not_origin",
        "nsb",
        "sb",
        "email_type",
        "item_domain",
        "service",
        "not_service",
        "subscription",
        "balance_min",
        "usage_percent_max",
        "kyc_verified",
        "cookies",
        "reg",
        "transactions",
        "tel",
    ),
}


def curated_filters(category: SearchableCategory) -> tuple[str, ...]:
    """The short list for this category; the shared core when nobody has curated it yet.

    Returning the core rather than an empty tuple matters: an uncurated category would otherwise
    open with a bare "Все фильтры (58)" and no starting point at all.
    """
    return _BY_CATEGORY.get(category, _CORE)
